// Mocks generated by Mockito 5.4.6 from annotations
// in zenith/test/services/exercise_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:sqflite/sqflite.dart' as _i2;
import 'package:zenith/models/exercise.dart' as _i3;
import 'package:zenith/models/muscle_group.dart' as _i8;
import 'package:zenith/services/dao/exercise_dao.dart' as _i4;
import 'package:zenith/services/dao/muscle_group_dao.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExercise_1 extends _i1.SmartFake implements _i3.Exercise {
  _FakeExercise_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExerciseDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseDao extends _i1.Mock implements _i4.ExerciseDao {
  MockExerciseDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i6.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i6.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i6.Future<_i2.Database>);

  @override
  _i3.Exercise fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeExercise_1(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i3.Exercise);

  @override
  Map<String, dynamic> toMap(_i3.Exercise? exercise) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [exercise]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i6.Future<List<_i3.Exercise>> getAllExercises() =>
      (super.noSuchMethod(
            Invocation.method(#getAllExercises, []),
            returnValue: _i6.Future<List<_i3.Exercise>>.value(<_i3.Exercise>[]),
          )
          as _i6.Future<List<_i3.Exercise>>);

  @override
  _i6.Future<_i3.Exercise?> getExerciseBySlug(String? slug) =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseBySlug, [slug]),
            returnValue: _i6.Future<_i3.Exercise?>.value(),
          )
          as _i6.Future<_i3.Exercise?>);

  @override
  _i6.Future<List<_i3.Exercise>> getExercisesByPrimaryMuscleGroup(
    String? muscleGroupName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExercisesByPrimaryMuscleGroup, [
              muscleGroupName,
            ]),
            returnValue: _i6.Future<List<_i3.Exercise>>.value(<_i3.Exercise>[]),
          )
          as _i6.Future<List<_i3.Exercise>>);

  @override
  _i6.Future<List<_i3.Exercise>> getExercisesBySecondaryMuscleGroup(
    String? muscleGroupName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExercisesBySecondaryMuscleGroup, [
              muscleGroupName,
            ]),
            returnValue: _i6.Future<List<_i3.Exercise>>.value(<_i3.Exercise>[]),
          )
          as _i6.Future<List<_i3.Exercise>>);

  @override
  _i6.Future<List<_i3.Exercise>> searchExercisesByName(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchExercisesByName, [query]),
            returnValue: _i6.Future<List<_i3.Exercise>>.value(<_i3.Exercise>[]),
          )
          as _i6.Future<List<_i3.Exercise>>);

  @override
  _i6.Future<int> insert(_i3.Exercise? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<int>> insertAll(List<_i3.Exercise>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i6.Future<List<int>>.value(<int>[]),
          )
          as _i6.Future<List<int>>);

  @override
  _i6.Future<List<_i3.Exercise>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i6.Future<List<_i3.Exercise>>.value(<_i3.Exercise>[]),
          )
          as _i6.Future<List<_i3.Exercise>>);

  @override
  _i6.Future<_i3.Exercise?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i6.Future<_i3.Exercise?>.value(),
          )
          as _i6.Future<_i3.Exercise?>);

  @override
  _i6.Future<int> update(_i3.Exercise? model, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i3.Exercise>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i6.Future<List<_i3.Exercise>>.value(<_i3.Exercise>[]),
          )
          as _i6.Future<List<_i3.Exercise>>);

  @override
  _i6.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);
}

/// A class which mocks [MuscleGroupDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockMuscleGroupDao extends _i1.Mock implements _i7.MuscleGroupDao {
  MockMuscleGroupDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i6.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i6.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i6.Future<_i2.Database>);

  @override
  _i8.MuscleGroup fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _i8.MuscleGroup.chest,
          )
          as _i8.MuscleGroup);

  @override
  Map<String, dynamic> toMap(_i8.MuscleGroup? muscleGroup) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [muscleGroup]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i6.Future<List<_i8.MuscleGroup>> getAllMuscleGroups() =>
      (super.noSuchMethod(
            Invocation.method(#getAllMuscleGroups, []),
            returnValue: _i6.Future<List<_i8.MuscleGroup>>.value(
              <_i8.MuscleGroup>[],
            ),
          )
          as _i6.Future<List<_i8.MuscleGroup>>);

  @override
  _i6.Future<_i8.MuscleGroup?> getMuscleGroupByName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getMuscleGroupByName, [name]),
            returnValue: _i6.Future<_i8.MuscleGroup?>.value(),
          )
          as _i6.Future<_i8.MuscleGroup?>);

  @override
  _i6.Future<int> insert(_i8.MuscleGroup? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<int>> insertAll(List<_i8.MuscleGroup>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i6.Future<List<int>>.value(<int>[]),
          )
          as _i6.Future<List<int>>);

  @override
  _i6.Future<List<_i8.MuscleGroup>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i6.Future<List<_i8.MuscleGroup>>.value(
              <_i8.MuscleGroup>[],
            ),
          )
          as _i6.Future<List<_i8.MuscleGroup>>);

  @override
  _i6.Future<_i8.MuscleGroup?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i6.Future<_i8.MuscleGroup?>.value(),
          )
          as _i6.Future<_i8.MuscleGroup?>);

  @override
  _i6.Future<int> update(_i8.MuscleGroup? model, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i8.MuscleGroup>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i6.Future<List<_i8.MuscleGroup>>.value(
              <_i8.MuscleGroup>[],
            ),
          )
          as _i6.Future<List<_i8.MuscleGroup>>);

  @override
  _i6.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);
}
