// Mocks generated by Mockito 5.4.6 from annotations
// in zenith/test/services/export_import_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:sqflite/sqflite.dart' as _i2;
import 'package:zenith/models/exercise.dart' as _i8;
import 'package:zenith/models/muscle_group.dart' as _i19;
import 'package:zenith/models/user_data.dart' as _i3;
import 'package:zenith/models/workout.dart' as _i4;
import 'package:zenith/models/workout_exercise.dart' as _i6;
import 'package:zenith/models/workout_folder.dart' as _i5;
import 'package:zenith/models/workout_set.dart' as _i7;
import 'package:zenith/services/dao/exercise_dao.dart' as _i17;
import 'package:zenith/services/dao/muscle_group_dao.dart' as _i18;
import 'package:zenith/services/dao/user_dao.dart' as _i9;
import 'package:zenith/services/dao/weight_entry_dao.dart' as _i12;
import 'package:zenith/services/dao/workout_dao.dart' as _i13;
import 'package:zenith/services/dao/workout_exercise_dao.dart' as _i15;
import 'package:zenith/services/dao/workout_folder_dao.dart' as _i14;
import 'package:zenith/services/dao/workout_set_dao.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserData_1 extends _i1.SmartFake implements _i3.UserData {
  _FakeUserData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWeightEntry_2 extends _i1.SmartFake implements _i3.WeightEntry {
  _FakeWeightEntry_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWorkout_3 extends _i1.SmartFake implements _i4.Workout {
  _FakeWorkout_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWorkoutFolder_4 extends _i1.SmartFake implements _i5.WorkoutFolder {
  _FakeWorkoutFolder_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWorkoutExercise_5 extends _i1.SmartFake
    implements _i6.WorkoutExercise {
  _FakeWorkoutExercise_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWorkoutSet_6 extends _i1.SmartFake implements _i7.WorkoutSet {
  _FakeWorkoutSet_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExercise_7 extends _i1.SmartFake implements _i8.Exercise {
  _FakeExercise_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDao extends _i1.Mock implements _i9.UserDao {
  MockUserDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i11.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i11.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i11.Future<_i2.Database>);

  @override
  _i3.UserData fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeUserData_1(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i3.UserData);

  @override
  Map<String, dynamic> toMap(_i3.UserData? userData) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [userData]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i11.Future<_i3.UserData?> getUserDataById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUserDataById, [id]),
            returnValue: _i11.Future<_i3.UserData?>.value(),
          )
          as _i11.Future<_i3.UserData?>);

  @override
  _i11.Future<int> updateUserData(_i3.UserData? userData) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserData, [userData]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> insert(_i3.UserData? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<List<int>> insertAll(List<_i3.UserData>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i11.Future<List<int>>.value(<int>[]),
          )
          as _i11.Future<List<int>>);

  @override
  _i11.Future<List<_i3.UserData>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i11.Future<List<_i3.UserData>>.value(
              <_i3.UserData>[],
            ),
          )
          as _i11.Future<List<_i3.UserData>>);

  @override
  _i11.Future<_i3.UserData?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i11.Future<_i3.UserData?>.value(),
          )
          as _i11.Future<_i3.UserData?>);

  @override
  _i11.Future<int> update(_i3.UserData? model, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<List<_i3.UserData>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i11.Future<List<_i3.UserData>>.value(
              <_i3.UserData>[],
            ),
          )
          as _i11.Future<List<_i3.UserData>>);

  @override
  _i11.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);
}

/// A class which mocks [WeightEntryDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeightEntryDao extends _i1.Mock implements _i12.WeightEntryDao {
  MockWeightEntryDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i11.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i11.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i11.Future<_i2.Database>);

  @override
  _i3.WeightEntry fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeWeightEntry_2(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i3.WeightEntry);

  @override
  Map<String, dynamic> toMap(_i3.WeightEntry? weightEntry) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [weightEntry]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i11.Future<List<_i3.WeightEntry>> getWeightEntriesByUserId(
    String? userDataId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWeightEntriesByUserId, [userDataId]),
            returnValue: _i11.Future<List<_i3.WeightEntry>>.value(
              <_i3.WeightEntry>[],
            ),
          )
          as _i11.Future<List<_i3.WeightEntry>>);

  @override
  _i11.Future<int> addWeightEntryForUser(
    String? userDataId,
    _i3.WeightEntry? weightEntry,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addWeightEntryForUser, [
              userDataId,
              weightEntry,
            ]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> updateWeightEntry(
    String? userDataId,
    _i3.WeightEntry? weightEntry,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateWeightEntry, [userDataId, weightEntry]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> deleteWeightEntry(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWeightEntry, [id]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> insert(_i3.WeightEntry? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<List<int>> insertAll(List<_i3.WeightEntry>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i11.Future<List<int>>.value(<int>[]),
          )
          as _i11.Future<List<int>>);

  @override
  _i11.Future<List<_i3.WeightEntry>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i11.Future<List<_i3.WeightEntry>>.value(
              <_i3.WeightEntry>[],
            ),
          )
          as _i11.Future<List<_i3.WeightEntry>>);

  @override
  _i11.Future<_i3.WeightEntry?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i11.Future<_i3.WeightEntry?>.value(),
          )
          as _i11.Future<_i3.WeightEntry?>);

  @override
  _i11.Future<int> update(_i3.WeightEntry? model, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<List<_i3.WeightEntry>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i11.Future<List<_i3.WeightEntry>>.value(
              <_i3.WeightEntry>[],
            ),
          )
          as _i11.Future<List<_i3.WeightEntry>>);

  @override
  _i11.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);
}

/// A class which mocks [WorkoutDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutDao extends _i1.Mock implements _i13.WorkoutDao {
  MockWorkoutDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i11.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i11.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i11.Future<_i2.Database>);

  @override
  _i4.Workout fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeWorkout_3(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i4.Workout);

  @override
  Map<String, dynamic> toMap(_i4.Workout? workout) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [workout]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i11.Future<_i4.Workout?> getWorkoutById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutById, [id]),
            returnValue: _i11.Future<_i4.Workout?>.value(),
          )
          as _i11.Future<_i4.Workout?>);

  @override
  _i11.Future<List<_i4.Workout>> getAllWorkouts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllWorkouts, []),
            returnValue: _i11.Future<List<_i4.Workout>>.value(<_i4.Workout>[]),
          )
          as _i11.Future<List<_i4.Workout>>);

  @override
  _i11.Future<List<_i4.Workout>> getWorkoutsByFolderId(String? folderId) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutsByFolderId, [folderId]),
            returnValue: _i11.Future<List<_i4.Workout>>.value(<_i4.Workout>[]),
          )
          as _i11.Future<List<_i4.Workout>>);

  @override
  _i11.Future<List<_i4.Workout>> getWorkoutsByStatus(
    _i4.WorkoutStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutsByStatus, [status]),
            returnValue: _i11.Future<List<_i4.Workout>>.value(<_i4.Workout>[]),
          )
          as _i11.Future<List<_i4.Workout>>);

  @override
  _i11.Future<List<_i4.Workout>> getTemplateWorkouts() =>
      (super.noSuchMethod(
            Invocation.method(#getTemplateWorkouts, []),
            returnValue: _i11.Future<List<_i4.Workout>>.value(<_i4.Workout>[]),
          )
          as _i11.Future<List<_i4.Workout>>);

  @override
  _i11.Future<List<_i4.Workout>> getInProgressWorkouts() =>
      (super.noSuchMethod(
            Invocation.method(#getInProgressWorkouts, []),
            returnValue: _i11.Future<List<_i4.Workout>>.value(<_i4.Workout>[]),
          )
          as _i11.Future<List<_i4.Workout>>);

  @override
  _i11.Future<List<_i4.Workout>> getCompletedWorkouts() =>
      (super.noSuchMethod(
            Invocation.method(#getCompletedWorkouts, []),
            returnValue: _i11.Future<List<_i4.Workout>>.value(<_i4.Workout>[]),
          )
          as _i11.Future<List<_i4.Workout>>);

  @override
  _i11.Future<List<_i4.Workout>> getWorkoutsByTemplateId(String? templateId) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutsByTemplateId, [templateId]),
            returnValue: _i11.Future<List<_i4.Workout>>.value(<_i4.Workout>[]),
          )
          as _i11.Future<List<_i4.Workout>>);

  @override
  _i11.Future<List<_i4.Workout>> getWorkoutsInDateRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutsInDateRange, [startDate, endDate]),
            returnValue: _i11.Future<List<_i4.Workout>>.value(<_i4.Workout>[]),
          )
          as _i11.Future<List<_i4.Workout>>);

  @override
  _i11.Future<int> updateWorkout(_i4.Workout? workout) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkout, [workout]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> deleteWorkout(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkout, [id]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> insert(_i4.Workout? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<List<int>> insertAll(List<_i4.Workout>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i11.Future<List<int>>.value(<int>[]),
          )
          as _i11.Future<List<int>>);

  @override
  _i11.Future<List<_i4.Workout>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i11.Future<List<_i4.Workout>>.value(<_i4.Workout>[]),
          )
          as _i11.Future<List<_i4.Workout>>);

  @override
  _i11.Future<_i4.Workout?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i11.Future<_i4.Workout?>.value(),
          )
          as _i11.Future<_i4.Workout?>);

  @override
  _i11.Future<int> update(_i4.Workout? model, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<List<_i4.Workout>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i11.Future<List<_i4.Workout>>.value(<_i4.Workout>[]),
          )
          as _i11.Future<List<_i4.Workout>>);

  @override
  _i11.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);
}

/// A class which mocks [WorkoutFolderDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutFolderDao extends _i1.Mock implements _i14.WorkoutFolderDao {
  MockWorkoutFolderDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i11.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i11.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i11.Future<_i2.Database>);

  @override
  _i5.WorkoutFolder fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeWorkoutFolder_4(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i5.WorkoutFolder);

  @override
  Map<String, dynamic> toMap(_i5.WorkoutFolder? workoutFolder) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [workoutFolder]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i11.Future<_i5.WorkoutFolder?> getWorkoutFolderById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutFolderById, [id]),
            returnValue: _i11.Future<_i5.WorkoutFolder?>.value(),
          )
          as _i11.Future<_i5.WorkoutFolder?>);

  @override
  _i11.Future<List<_i5.WorkoutFolder>> getAllWorkoutFoldersOrdered() =>
      (super.noSuchMethod(
            Invocation.method(#getAllWorkoutFoldersOrdered, []),
            returnValue: _i11.Future<List<_i5.WorkoutFolder>>.value(
              <_i5.WorkoutFolder>[],
            ),
          )
          as _i11.Future<List<_i5.WorkoutFolder>>);

  @override
  _i11.Future<int> updateWorkoutFolder(_i5.WorkoutFolder? workoutFolder) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkoutFolder, [workoutFolder]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> deleteWorkoutFolder(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkoutFolder, [id]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> insert(_i5.WorkoutFolder? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<List<int>> insertAll(List<_i5.WorkoutFolder>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i11.Future<List<int>>.value(<int>[]),
          )
          as _i11.Future<List<int>>);

  @override
  _i11.Future<List<_i5.WorkoutFolder>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i11.Future<List<_i5.WorkoutFolder>>.value(
              <_i5.WorkoutFolder>[],
            ),
          )
          as _i11.Future<List<_i5.WorkoutFolder>>);

  @override
  _i11.Future<_i5.WorkoutFolder?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i11.Future<_i5.WorkoutFolder?>.value(),
          )
          as _i11.Future<_i5.WorkoutFolder?>);

  @override
  _i11.Future<int> update(
    _i5.WorkoutFolder? model, {
    String? idColumn = 'id',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<List<_i5.WorkoutFolder>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i11.Future<List<_i5.WorkoutFolder>>.value(
              <_i5.WorkoutFolder>[],
            ),
          )
          as _i11.Future<List<_i5.WorkoutFolder>>);

  @override
  _i11.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);
}

/// A class which mocks [WorkoutExerciseDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutExerciseDao extends _i1.Mock
    implements _i15.WorkoutExerciseDao {
  MockWorkoutExerciseDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i11.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i11.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i11.Future<_i2.Database>);

  @override
  _i6.WorkoutExercise fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeWorkoutExercise_5(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i6.WorkoutExercise);

  @override
  Map<String, dynamic> toMap(_i6.WorkoutExercise? workoutExercise) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [workoutExercise]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i11.Future<_i6.WorkoutExercise?> getWorkoutExerciseById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutExerciseById, [id]),
            returnValue: _i11.Future<_i6.WorkoutExercise?>.value(),
          )
          as _i11.Future<_i6.WorkoutExercise?>);

  @override
  _i11.Future<List<_i6.WorkoutExercise>> getWorkoutExercisesByWorkoutId(
    String? workoutId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutExercisesByWorkoutId, [workoutId]),
            returnValue: _i11.Future<List<_i6.WorkoutExercise>>.value(
              <_i6.WorkoutExercise>[],
            ),
          )
          as _i11.Future<List<_i6.WorkoutExercise>>);

  @override
  _i11.Future<List<_i6.WorkoutExercise>> getWorkoutExercisesByExerciseSlug(
    String? exerciseSlug,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutExercisesByExerciseSlug, [
              exerciseSlug,
            ]),
            returnValue: _i11.Future<List<_i6.WorkoutExercise>>.value(
              <_i6.WorkoutExercise>[],
            ),
          )
          as _i11.Future<List<_i6.WorkoutExercise>>);

  @override
  _i11.Future<int> updateWorkoutExercise(
    _i6.WorkoutExercise? workoutExercise,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkoutExercise, [workoutExercise]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> deleteWorkoutExercise(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkoutExercise, [id]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> deleteWorkoutExercisesByWorkoutId(String? workoutId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkoutExercisesByWorkoutId, [workoutId]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> insert(_i6.WorkoutExercise? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<List<int>> insertAll(List<_i6.WorkoutExercise>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i11.Future<List<int>>.value(<int>[]),
          )
          as _i11.Future<List<int>>);

  @override
  _i11.Future<List<_i6.WorkoutExercise>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i11.Future<List<_i6.WorkoutExercise>>.value(
              <_i6.WorkoutExercise>[],
            ),
          )
          as _i11.Future<List<_i6.WorkoutExercise>>);

  @override
  _i11.Future<_i6.WorkoutExercise?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i11.Future<_i6.WorkoutExercise?>.value(),
          )
          as _i11.Future<_i6.WorkoutExercise?>);

  @override
  _i11.Future<int> update(
    _i6.WorkoutExercise? model, {
    String? idColumn = 'id',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<List<_i6.WorkoutExercise>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i11.Future<List<_i6.WorkoutExercise>>.value(
              <_i6.WorkoutExercise>[],
            ),
          )
          as _i11.Future<List<_i6.WorkoutExercise>>);

  @override
  _i11.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);
}

/// A class which mocks [WorkoutSetDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutSetDao extends _i1.Mock implements _i16.WorkoutSetDao {
  MockWorkoutSetDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i11.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i11.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i11.Future<_i2.Database>);

  @override
  _i7.WorkoutSet fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeWorkoutSet_6(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i7.WorkoutSet);

  @override
  Map<String, dynamic> toMap(_i7.WorkoutSet? workoutSet) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [workoutSet]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i11.Future<_i7.WorkoutSet?> getWorkoutSetById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutSetById, [id]),
            returnValue: _i11.Future<_i7.WorkoutSet?>.value(),
          )
          as _i11.Future<_i7.WorkoutSet?>);

  @override
  _i11.Future<List<_i7.WorkoutSet>> getWorkoutSetsByWorkoutExerciseId(
    String? workoutExerciseId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutSetsByWorkoutExerciseId, [
              workoutExerciseId,
            ]),
            returnValue: _i11.Future<List<_i7.WorkoutSet>>.value(
              <_i7.WorkoutSet>[],
            ),
          )
          as _i11.Future<List<_i7.WorkoutSet>>);

  @override
  _i11.Future<List<_i7.WorkoutSet>> getCompletedWorkoutSetsByWorkoutExerciseId(
    String? workoutExerciseId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCompletedWorkoutSetsByWorkoutExerciseId, [
              workoutExerciseId,
            ]),
            returnValue: _i11.Future<List<_i7.WorkoutSet>>.value(
              <_i7.WorkoutSet>[],
            ),
          )
          as _i11.Future<List<_i7.WorkoutSet>>);

  @override
  _i11.Future<int> updateWorkoutSet(_i7.WorkoutSet? workoutSet) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkoutSet, [workoutSet]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> deleteWorkoutSet(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkoutSet, [id]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> deleteWorkoutSetsByWorkoutExerciseId(
    String? workoutExerciseId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkoutSetsByWorkoutExerciseId, [
              workoutExerciseId,
            ]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> insert(_i7.WorkoutSet? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<List<int>> insertAll(List<_i7.WorkoutSet>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i11.Future<List<int>>.value(<int>[]),
          )
          as _i11.Future<List<int>>);

  @override
  _i11.Future<List<_i7.WorkoutSet>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i11.Future<List<_i7.WorkoutSet>>.value(
              <_i7.WorkoutSet>[],
            ),
          )
          as _i11.Future<List<_i7.WorkoutSet>>);

  @override
  _i11.Future<_i7.WorkoutSet?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i11.Future<_i7.WorkoutSet?>.value(),
          )
          as _i11.Future<_i7.WorkoutSet?>);

  @override
  _i11.Future<int> update(_i7.WorkoutSet? model, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<List<_i7.WorkoutSet>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i11.Future<List<_i7.WorkoutSet>>.value(
              <_i7.WorkoutSet>[],
            ),
          )
          as _i11.Future<List<_i7.WorkoutSet>>);

  @override
  _i11.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);
}

/// A class which mocks [ExerciseDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseDao extends _i1.Mock implements _i17.ExerciseDao {
  MockExerciseDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i11.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i11.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i11.Future<_i2.Database>);

  @override
  _i8.Exercise fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeExercise_7(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i8.Exercise);

  @override
  Map<String, dynamic> toMap(_i8.Exercise? exercise) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [exercise]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i11.Future<List<_i8.Exercise>> getAllExercises() =>
      (super.noSuchMethod(
            Invocation.method(#getAllExercises, []),
            returnValue: _i11.Future<List<_i8.Exercise>>.value(
              <_i8.Exercise>[],
            ),
          )
          as _i11.Future<List<_i8.Exercise>>);

  @override
  _i11.Future<_i8.Exercise?> getExerciseBySlug(String? slug) =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseBySlug, [slug]),
            returnValue: _i11.Future<_i8.Exercise?>.value(),
          )
          as _i11.Future<_i8.Exercise?>);

  @override
  _i11.Future<List<_i8.Exercise>> getExercisesByPrimaryMuscleGroup(
    String? muscleGroupName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExercisesByPrimaryMuscleGroup, [
              muscleGroupName,
            ]),
            returnValue: _i11.Future<List<_i8.Exercise>>.value(
              <_i8.Exercise>[],
            ),
          )
          as _i11.Future<List<_i8.Exercise>>);

  @override
  _i11.Future<List<_i8.Exercise>> getExercisesBySecondaryMuscleGroup(
    String? muscleGroupName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExercisesBySecondaryMuscleGroup, [
              muscleGroupName,
            ]),
            returnValue: _i11.Future<List<_i8.Exercise>>.value(
              <_i8.Exercise>[],
            ),
          )
          as _i11.Future<List<_i8.Exercise>>);

  @override
  _i11.Future<List<_i8.Exercise>> searchExercisesByName(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchExercisesByName, [query]),
            returnValue: _i11.Future<List<_i8.Exercise>>.value(
              <_i8.Exercise>[],
            ),
          )
          as _i11.Future<List<_i8.Exercise>>);

  @override
  _i11.Future<int> insert(_i8.Exercise? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<List<int>> insertAll(List<_i8.Exercise>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i11.Future<List<int>>.value(<int>[]),
          )
          as _i11.Future<List<int>>);

  @override
  _i11.Future<List<_i8.Exercise>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i11.Future<List<_i8.Exercise>>.value(
              <_i8.Exercise>[],
            ),
          )
          as _i11.Future<List<_i8.Exercise>>);

  @override
  _i11.Future<_i8.Exercise?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i11.Future<_i8.Exercise?>.value(),
          )
          as _i11.Future<_i8.Exercise?>);

  @override
  _i11.Future<int> update(_i8.Exercise? model, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<List<_i8.Exercise>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i11.Future<List<_i8.Exercise>>.value(
              <_i8.Exercise>[],
            ),
          )
          as _i11.Future<List<_i8.Exercise>>);

  @override
  _i11.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);
}

/// A class which mocks [MuscleGroupDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockMuscleGroupDao extends _i1.Mock implements _i18.MuscleGroupDao {
  MockMuscleGroupDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i11.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i11.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i11.Future<_i2.Database>);

  @override
  _i19.MuscleGroup fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _i19.MuscleGroup.chest,
          )
          as _i19.MuscleGroup);

  @override
  Map<String, dynamic> toMap(_i19.MuscleGroup? muscleGroup) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [muscleGroup]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i11.Future<List<_i19.MuscleGroup>> getAllMuscleGroups() =>
      (super.noSuchMethod(
            Invocation.method(#getAllMuscleGroups, []),
            returnValue: _i11.Future<List<_i19.MuscleGroup>>.value(
              <_i19.MuscleGroup>[],
            ),
          )
          as _i11.Future<List<_i19.MuscleGroup>>);

  @override
  _i11.Future<_i19.MuscleGroup?> getMuscleGroupByName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getMuscleGroupByName, [name]),
            returnValue: _i11.Future<_i19.MuscleGroup?>.value(),
          )
          as _i11.Future<_i19.MuscleGroup?>);

  @override
  _i11.Future<int> insert(_i19.MuscleGroup? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<List<int>> insertAll(List<_i19.MuscleGroup>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i11.Future<List<int>>.value(<int>[]),
          )
          as _i11.Future<List<int>>);

  @override
  _i11.Future<List<_i19.MuscleGroup>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i11.Future<List<_i19.MuscleGroup>>.value(
              <_i19.MuscleGroup>[],
            ),
          )
          as _i11.Future<List<_i19.MuscleGroup>>);

  @override
  _i11.Future<_i19.MuscleGroup?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i11.Future<_i19.MuscleGroup?>.value(),
          )
          as _i11.Future<_i19.MuscleGroup?>);

  @override
  _i11.Future<int> update(_i19.MuscleGroup? model, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<List<_i19.MuscleGroup>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i11.Future<List<_i19.MuscleGroup>>.value(
              <_i19.MuscleGroup>[],
            ),
          )
          as _i11.Future<List<_i19.MuscleGroup>>);

  @override
  _i11.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);
}
