// Mocks generated by Mockito 5.4.6 from annotations
// in zenith/test/services/export_import_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;

import 'package:logging/logging.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:sqflite/sqflite.dart' as _i3;
import 'package:zenith/models/exercise.dart' as _i9;
import 'package:zenith/models/muscle_group.dart' as _i20;
import 'package:zenith/models/user_data.dart' as _i4;
import 'package:zenith/models/workout.dart' as _i5;
import 'package:zenith/models/workout_exercise.dart' as _i7;
import 'package:zenith/models/workout_folder.dart' as _i6;
import 'package:zenith/models/workout_set.dart' as _i8;
import 'package:zenith/services/dao/exercise_dao.dart' as _i18;
import 'package:zenith/services/dao/muscle_group_dao.dart' as _i19;
import 'package:zenith/services/dao/user_dao.dart' as _i10;
import 'package:zenith/services/dao/weight_entry_dao.dart' as _i13;
import 'package:zenith/services/dao/workout_dao.dart' as _i14;
import 'package:zenith/services/dao/workout_exercise_dao.dart' as _i16;
import 'package:zenith/services/dao/workout_folder_dao.dart' as _i15;
import 'package:zenith/services/dao/workout_set_dao.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLogger_0 extends _i1.SmartFake implements _i2.Logger {
  _FakeLogger_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabase_1 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserData_2 extends _i1.SmartFake implements _i4.UserData {
  _FakeUserData_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWeightEntry_3 extends _i1.SmartFake implements _i4.WeightEntry {
  _FakeWeightEntry_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWorkout_4 extends _i1.SmartFake implements _i5.Workout {
  _FakeWorkout_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWorkoutFolder_5 extends _i1.SmartFake implements _i6.WorkoutFolder {
  _FakeWorkoutFolder_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWorkoutExercise_6 extends _i1.SmartFake
    implements _i7.WorkoutExercise {
  _FakeWorkoutExercise_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWorkoutSet_7 extends _i1.SmartFake implements _i8.WorkoutSet {
  _FakeWorkoutSet_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExercise_8 extends _i1.SmartFake implements _i9.Exercise {
  _FakeExercise_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDao extends _i1.Mock implements _i10.UserDao {
  MockUserDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i2.Logger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeLogger_0(this, Invocation.getter(#logger)),
          )
          as _i2.Logger);

  @override
  _i12.Future<_i3.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i12.Future<_i3.Database>.value(
              _FakeDatabase_1(this, Invocation.getter(#database)),
            ),
          )
          as _i12.Future<_i3.Database>);

  @override
  _i4.UserData fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeUserData_2(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i4.UserData);

  @override
  Map<String, dynamic> toMap(_i4.UserData? userData) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [userData]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i12.Future<_i4.UserData?> getUserDataById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUserDataById, [id]),
            returnValue: _i12.Future<_i4.UserData?>.value(),
          )
          as _i12.Future<_i4.UserData?>);

  @override
  _i12.Future<int> updateUserData(_i4.UserData? userData) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserData, [userData]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> insert(_i4.UserData? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<List<int>> insertAll(List<_i4.UserData>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i12.Future<List<int>>.value(<int>[]),
          )
          as _i12.Future<List<int>>);

  @override
  _i12.Future<List<_i4.UserData>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i12.Future<List<_i4.UserData>>.value(
              <_i4.UserData>[],
            ),
          )
          as _i12.Future<List<_i4.UserData>>);

  @override
  _i12.Future<_i4.UserData?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i4.UserData?>.value(),
          )
          as _i12.Future<_i4.UserData?>);

  @override
  _i12.Future<int> update(_i4.UserData? model, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<List<_i4.UserData>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i12.Future<List<_i4.UserData>>.value(
              <_i4.UserData>[],
            ),
          )
          as _i12.Future<List<_i4.UserData>>);

  @override
  _i12.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [WeightEntryDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeightEntryDao extends _i1.Mock implements _i13.WeightEntryDao {
  MockWeightEntryDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i2.Logger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeLogger_0(this, Invocation.getter(#logger)),
          )
          as _i2.Logger);

  @override
  _i12.Future<_i3.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i12.Future<_i3.Database>.value(
              _FakeDatabase_1(this, Invocation.getter(#database)),
            ),
          )
          as _i12.Future<_i3.Database>);

  @override
  _i4.WeightEntry fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeWeightEntry_3(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i4.WeightEntry);

  @override
  Map<String, dynamic> toMap(_i4.WeightEntry? weightEntry) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [weightEntry]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i12.Future<List<_i4.WeightEntry>> getWeightEntriesByUserId(
    String? userDataId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWeightEntriesByUserId, [userDataId]),
            returnValue: _i12.Future<List<_i4.WeightEntry>>.value(
              <_i4.WeightEntry>[],
            ),
          )
          as _i12.Future<List<_i4.WeightEntry>>);

  @override
  _i12.Future<int> addWeightEntryForUser(
    String? userDataId,
    _i4.WeightEntry? weightEntry,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addWeightEntryForUser, [
              userDataId,
              weightEntry,
            ]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> updateWeightEntry(
    String? userDataId,
    _i4.WeightEntry? weightEntry,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateWeightEntry, [userDataId, weightEntry]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> deleteWeightEntry(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWeightEntry, [id]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> insert(_i4.WeightEntry? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<List<int>> insertAll(List<_i4.WeightEntry>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i12.Future<List<int>>.value(<int>[]),
          )
          as _i12.Future<List<int>>);

  @override
  _i12.Future<List<_i4.WeightEntry>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i12.Future<List<_i4.WeightEntry>>.value(
              <_i4.WeightEntry>[],
            ),
          )
          as _i12.Future<List<_i4.WeightEntry>>);

  @override
  _i12.Future<_i4.WeightEntry?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i4.WeightEntry?>.value(),
          )
          as _i12.Future<_i4.WeightEntry?>);

  @override
  _i12.Future<int> update(_i4.WeightEntry? model, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<List<_i4.WeightEntry>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i12.Future<List<_i4.WeightEntry>>.value(
              <_i4.WeightEntry>[],
            ),
          )
          as _i12.Future<List<_i4.WeightEntry>>);

  @override
  _i12.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [WorkoutDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutDao extends _i1.Mock implements _i14.WorkoutDao {
  MockWorkoutDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i2.Logger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeLogger_0(this, Invocation.getter(#logger)),
          )
          as _i2.Logger);

  @override
  _i12.Future<_i3.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i12.Future<_i3.Database>.value(
              _FakeDatabase_1(this, Invocation.getter(#database)),
            ),
          )
          as _i12.Future<_i3.Database>);

  @override
  _i5.Workout fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeWorkout_4(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i5.Workout);

  @override
  Map<String, dynamic> toMap(_i5.Workout? workout) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [workout]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i12.Future<_i5.Workout?> getWorkoutById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutById, [id]),
            returnValue: _i12.Future<_i5.Workout?>.value(),
          )
          as _i12.Future<_i5.Workout?>);

  @override
  _i12.Future<List<_i5.Workout>> getAllWorkouts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllWorkouts, []),
            returnValue: _i12.Future<List<_i5.Workout>>.value(<_i5.Workout>[]),
          )
          as _i12.Future<List<_i5.Workout>>);

  @override
  _i12.Future<List<_i5.Workout>> getWorkoutsByFolderId(String? folderId) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutsByFolderId, [folderId]),
            returnValue: _i12.Future<List<_i5.Workout>>.value(<_i5.Workout>[]),
          )
          as _i12.Future<List<_i5.Workout>>);

  @override
  _i12.Future<List<_i5.Workout>> getWorkoutsByStatus(
    _i5.WorkoutStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutsByStatus, [status]),
            returnValue: _i12.Future<List<_i5.Workout>>.value(<_i5.Workout>[]),
          )
          as _i12.Future<List<_i5.Workout>>);

  @override
  _i12.Future<List<_i5.Workout>> getTemplateWorkouts() =>
      (super.noSuchMethod(
            Invocation.method(#getTemplateWorkouts, []),
            returnValue: _i12.Future<List<_i5.Workout>>.value(<_i5.Workout>[]),
          )
          as _i12.Future<List<_i5.Workout>>);

  @override
  _i12.Future<List<_i5.Workout>> getInProgressWorkouts() =>
      (super.noSuchMethod(
            Invocation.method(#getInProgressWorkouts, []),
            returnValue: _i12.Future<List<_i5.Workout>>.value(<_i5.Workout>[]),
          )
          as _i12.Future<List<_i5.Workout>>);

  @override
  _i12.Future<List<_i5.Workout>> getCompletedWorkouts() =>
      (super.noSuchMethod(
            Invocation.method(#getCompletedWorkouts, []),
            returnValue: _i12.Future<List<_i5.Workout>>.value(<_i5.Workout>[]),
          )
          as _i12.Future<List<_i5.Workout>>);

  @override
  _i12.Future<List<_i5.Workout>> getWorkoutsByTemplateId(String? templateId) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutsByTemplateId, [templateId]),
            returnValue: _i12.Future<List<_i5.Workout>>.value(<_i5.Workout>[]),
          )
          as _i12.Future<List<_i5.Workout>>);

  @override
  _i12.Future<List<_i5.Workout>> getWorkoutsInDateRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutsInDateRange, [startDate, endDate]),
            returnValue: _i12.Future<List<_i5.Workout>>.value(<_i5.Workout>[]),
          )
          as _i12.Future<List<_i5.Workout>>);

  @override
  _i12.Future<int> updateWorkout(_i5.Workout? workout) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkout, [workout]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> deleteWorkout(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkout, [id]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> insert(_i5.Workout? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<List<int>> insertAll(List<_i5.Workout>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i12.Future<List<int>>.value(<int>[]),
          )
          as _i12.Future<List<int>>);

  @override
  _i12.Future<List<_i5.Workout>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i12.Future<List<_i5.Workout>>.value(<_i5.Workout>[]),
          )
          as _i12.Future<List<_i5.Workout>>);

  @override
  _i12.Future<_i5.Workout?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i5.Workout?>.value(),
          )
          as _i12.Future<_i5.Workout?>);

  @override
  _i12.Future<int> update(_i5.Workout? model, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<List<_i5.Workout>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i12.Future<List<_i5.Workout>>.value(<_i5.Workout>[]),
          )
          as _i12.Future<List<_i5.Workout>>);

  @override
  _i12.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [WorkoutFolderDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutFolderDao extends _i1.Mock implements _i15.WorkoutFolderDao {
  MockWorkoutFolderDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i2.Logger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeLogger_0(this, Invocation.getter(#logger)),
          )
          as _i2.Logger);

  @override
  _i12.Future<_i3.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i12.Future<_i3.Database>.value(
              _FakeDatabase_1(this, Invocation.getter(#database)),
            ),
          )
          as _i12.Future<_i3.Database>);

  @override
  _i6.WorkoutFolder fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeWorkoutFolder_5(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i6.WorkoutFolder);

  @override
  Map<String, dynamic> toMap(_i6.WorkoutFolder? workoutFolder) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [workoutFolder]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i12.Future<_i6.WorkoutFolder?> getWorkoutFolderById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutFolderById, [id]),
            returnValue: _i12.Future<_i6.WorkoutFolder?>.value(),
          )
          as _i12.Future<_i6.WorkoutFolder?>);

  @override
  _i12.Future<List<_i6.WorkoutFolder>> getAllWorkoutFoldersOrdered() =>
      (super.noSuchMethod(
            Invocation.method(#getAllWorkoutFoldersOrdered, []),
            returnValue: _i12.Future<List<_i6.WorkoutFolder>>.value(
              <_i6.WorkoutFolder>[],
            ),
          )
          as _i12.Future<List<_i6.WorkoutFolder>>);

  @override
  _i12.Future<int> updateWorkoutFolder(_i6.WorkoutFolder? workoutFolder) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkoutFolder, [workoutFolder]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> deleteWorkoutFolder(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkoutFolder, [id]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> insert(_i6.WorkoutFolder? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<List<int>> insertAll(List<_i6.WorkoutFolder>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i12.Future<List<int>>.value(<int>[]),
          )
          as _i12.Future<List<int>>);

  @override
  _i12.Future<List<_i6.WorkoutFolder>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i12.Future<List<_i6.WorkoutFolder>>.value(
              <_i6.WorkoutFolder>[],
            ),
          )
          as _i12.Future<List<_i6.WorkoutFolder>>);

  @override
  _i12.Future<_i6.WorkoutFolder?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i6.WorkoutFolder?>.value(),
          )
          as _i12.Future<_i6.WorkoutFolder?>);

  @override
  _i12.Future<int> update(
    _i6.WorkoutFolder? model, {
    String? idColumn = 'id',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<List<_i6.WorkoutFolder>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i12.Future<List<_i6.WorkoutFolder>>.value(
              <_i6.WorkoutFolder>[],
            ),
          )
          as _i12.Future<List<_i6.WorkoutFolder>>);

  @override
  _i12.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [WorkoutExerciseDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutExerciseDao extends _i1.Mock
    implements _i16.WorkoutExerciseDao {
  MockWorkoutExerciseDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i2.Logger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeLogger_0(this, Invocation.getter(#logger)),
          )
          as _i2.Logger);

  @override
  _i12.Future<_i3.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i12.Future<_i3.Database>.value(
              _FakeDatabase_1(this, Invocation.getter(#database)),
            ),
          )
          as _i12.Future<_i3.Database>);

  @override
  _i7.WorkoutExercise fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeWorkoutExercise_6(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i7.WorkoutExercise);

  @override
  Map<String, dynamic> toMap(_i7.WorkoutExercise? workoutExercise) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [workoutExercise]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i12.Future<_i7.WorkoutExercise?> getWorkoutExerciseById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutExerciseById, [id]),
            returnValue: _i12.Future<_i7.WorkoutExercise?>.value(),
          )
          as _i12.Future<_i7.WorkoutExercise?>);

  @override
  _i12.Future<List<_i7.WorkoutExercise>> getWorkoutExercisesByWorkoutId(
    String? workoutId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutExercisesByWorkoutId, [workoutId]),
            returnValue: _i12.Future<List<_i7.WorkoutExercise>>.value(
              <_i7.WorkoutExercise>[],
            ),
          )
          as _i12.Future<List<_i7.WorkoutExercise>>);

  @override
  _i12.Future<List<_i7.WorkoutExercise>> getWorkoutExercisesByWorkoutTemplateId(
    String? workoutTemplateId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutExercisesByWorkoutTemplateId, [
              workoutTemplateId,
            ]),
            returnValue: _i12.Future<List<_i7.WorkoutExercise>>.value(
              <_i7.WorkoutExercise>[],
            ),
          )
          as _i12.Future<List<_i7.WorkoutExercise>>);

  @override
  _i12.Future<List<_i7.WorkoutExercise>> getWorkoutExercisesByExerciseSlug(
    String? exerciseSlug,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutExercisesByExerciseSlug, [
              exerciseSlug,
            ]),
            returnValue: _i12.Future<List<_i7.WorkoutExercise>>.value(
              <_i7.WorkoutExercise>[],
            ),
          )
          as _i12.Future<List<_i7.WorkoutExercise>>);

  @override
  _i12.Future<int> updateWorkoutExercise(
    _i7.WorkoutExercise? workoutExercise,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkoutExercise, [workoutExercise]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> deleteWorkoutExercise(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkoutExercise, [id]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> deleteWorkoutExercisesByWorkoutId(String? workoutId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkoutExercisesByWorkoutId, [workoutId]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> deleteWorkoutExercisesByWorkoutTemplateId(
    String? workoutTemplateId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkoutExercisesByWorkoutTemplateId, [
              workoutTemplateId,
            ]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> insert(_i7.WorkoutExercise? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<List<int>> insertAll(List<_i7.WorkoutExercise>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i12.Future<List<int>>.value(<int>[]),
          )
          as _i12.Future<List<int>>);

  @override
  _i12.Future<List<_i7.WorkoutExercise>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i12.Future<List<_i7.WorkoutExercise>>.value(
              <_i7.WorkoutExercise>[],
            ),
          )
          as _i12.Future<List<_i7.WorkoutExercise>>);

  @override
  _i12.Future<_i7.WorkoutExercise?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i7.WorkoutExercise?>.value(),
          )
          as _i12.Future<_i7.WorkoutExercise?>);

  @override
  _i12.Future<int> update(
    _i7.WorkoutExercise? model, {
    String? idColumn = 'id',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<List<_i7.WorkoutExercise>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i12.Future<List<_i7.WorkoutExercise>>.value(
              <_i7.WorkoutExercise>[],
            ),
          )
          as _i12.Future<List<_i7.WorkoutExercise>>);

  @override
  _i12.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [WorkoutSetDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutSetDao extends _i1.Mock implements _i17.WorkoutSetDao {
  MockWorkoutSetDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i2.Logger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeLogger_0(this, Invocation.getter(#logger)),
          )
          as _i2.Logger);

  @override
  _i12.Future<_i3.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i12.Future<_i3.Database>.value(
              _FakeDatabase_1(this, Invocation.getter(#database)),
            ),
          )
          as _i12.Future<_i3.Database>);

  @override
  _i8.WorkoutSet fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeWorkoutSet_7(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i8.WorkoutSet);

  @override
  Map<String, dynamic> toMap(_i8.WorkoutSet? workoutSet) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [workoutSet]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i12.Future<_i8.WorkoutSet?> getWorkoutSetById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutSetById, [id]),
            returnValue: _i12.Future<_i8.WorkoutSet?>.value(),
          )
          as _i12.Future<_i8.WorkoutSet?>);

  @override
  _i12.Future<List<_i8.WorkoutSet>> getWorkoutSetsByWorkoutExerciseId(
    String? workoutExerciseId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutSetsByWorkoutExerciseId, [
              workoutExerciseId,
            ]),
            returnValue: _i12.Future<List<_i8.WorkoutSet>>.value(
              <_i8.WorkoutSet>[],
            ),
          )
          as _i12.Future<List<_i8.WorkoutSet>>);

  @override
  _i12.Future<List<_i8.WorkoutSet>> getCompletedWorkoutSetsByWorkoutExerciseId(
    String? workoutExerciseId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCompletedWorkoutSetsByWorkoutExerciseId, [
              workoutExerciseId,
            ]),
            returnValue: _i12.Future<List<_i8.WorkoutSet>>.value(
              <_i8.WorkoutSet>[],
            ),
          )
          as _i12.Future<List<_i8.WorkoutSet>>);

  @override
  _i12.Future<int> updateWorkoutSet(_i8.WorkoutSet? workoutSet) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkoutSet, [workoutSet]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> deleteWorkoutSet(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkoutSet, [id]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> deleteWorkoutSetsByWorkoutExerciseId(
    String? workoutExerciseId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkoutSetsByWorkoutExerciseId, [
              workoutExerciseId,
            ]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> insert(_i8.WorkoutSet? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<List<int>> insertAll(List<_i8.WorkoutSet>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i12.Future<List<int>>.value(<int>[]),
          )
          as _i12.Future<List<int>>);

  @override
  _i12.Future<List<_i8.WorkoutSet>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i12.Future<List<_i8.WorkoutSet>>.value(
              <_i8.WorkoutSet>[],
            ),
          )
          as _i12.Future<List<_i8.WorkoutSet>>);

  @override
  _i12.Future<_i8.WorkoutSet?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i8.WorkoutSet?>.value(),
          )
          as _i12.Future<_i8.WorkoutSet?>);

  @override
  _i12.Future<int> update(_i8.WorkoutSet? model, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<List<_i8.WorkoutSet>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i12.Future<List<_i8.WorkoutSet>>.value(
              <_i8.WorkoutSet>[],
            ),
          )
          as _i12.Future<List<_i8.WorkoutSet>>);

  @override
  _i12.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [ExerciseDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseDao extends _i1.Mock implements _i18.ExerciseDao {
  MockExerciseDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i2.Logger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeLogger_0(this, Invocation.getter(#logger)),
          )
          as _i2.Logger);

  @override
  _i12.Future<_i3.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i12.Future<_i3.Database>.value(
              _FakeDatabase_1(this, Invocation.getter(#database)),
            ),
          )
          as _i12.Future<_i3.Database>);

  @override
  _i9.Exercise fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeExercise_8(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i9.Exercise);

  @override
  Map<String, dynamic> toMap(_i9.Exercise? exercise) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [exercise]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i12.Future<List<_i9.Exercise>> getAllExercises() =>
      (super.noSuchMethod(
            Invocation.method(#getAllExercises, []),
            returnValue: _i12.Future<List<_i9.Exercise>>.value(
              <_i9.Exercise>[],
            ),
          )
          as _i12.Future<List<_i9.Exercise>>);

  @override
  _i12.Future<_i9.Exercise?> getExerciseBySlug(String? slug) =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseBySlug, [slug]),
            returnValue: _i12.Future<_i9.Exercise?>.value(),
          )
          as _i12.Future<_i9.Exercise?>);

  @override
  _i12.Future<List<_i9.Exercise>> getExercisesByPrimaryMuscleGroup(
    String? muscleGroupName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExercisesByPrimaryMuscleGroup, [
              muscleGroupName,
            ]),
            returnValue: _i12.Future<List<_i9.Exercise>>.value(
              <_i9.Exercise>[],
            ),
          )
          as _i12.Future<List<_i9.Exercise>>);

  @override
  _i12.Future<List<_i9.Exercise>> getExercisesBySecondaryMuscleGroup(
    String? muscleGroupName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExercisesBySecondaryMuscleGroup, [
              muscleGroupName,
            ]),
            returnValue: _i12.Future<List<_i9.Exercise>>.value(
              <_i9.Exercise>[],
            ),
          )
          as _i12.Future<List<_i9.Exercise>>);

  @override
  _i12.Future<List<_i9.Exercise>> searchExercisesByName(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchExercisesByName, [query]),
            returnValue: _i12.Future<List<_i9.Exercise>>.value(
              <_i9.Exercise>[],
            ),
          )
          as _i12.Future<List<_i9.Exercise>>);

  @override
  _i12.Future<int> insert(_i9.Exercise? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<List<int>> insertAll(List<_i9.Exercise>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i12.Future<List<int>>.value(<int>[]),
          )
          as _i12.Future<List<int>>);

  @override
  _i12.Future<List<_i9.Exercise>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i12.Future<List<_i9.Exercise>>.value(
              <_i9.Exercise>[],
            ),
          )
          as _i12.Future<List<_i9.Exercise>>);

  @override
  _i12.Future<_i9.Exercise?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i9.Exercise?>.value(),
          )
          as _i12.Future<_i9.Exercise?>);

  @override
  _i12.Future<int> update(_i9.Exercise? model, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<List<_i9.Exercise>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i12.Future<List<_i9.Exercise>>.value(
              <_i9.Exercise>[],
            ),
          )
          as _i12.Future<List<_i9.Exercise>>);

  @override
  _i12.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [MuscleGroupDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockMuscleGroupDao extends _i1.Mock implements _i19.MuscleGroupDao {
  MockMuscleGroupDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i2.Logger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeLogger_0(this, Invocation.getter(#logger)),
          )
          as _i2.Logger);

  @override
  _i12.Future<_i3.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i12.Future<_i3.Database>.value(
              _FakeDatabase_1(this, Invocation.getter(#database)),
            ),
          )
          as _i12.Future<_i3.Database>);

  @override
  _i20.MuscleGroup fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _i20.MuscleGroup.chest,
          )
          as _i20.MuscleGroup);

  @override
  Map<String, dynamic> toMap(_i20.MuscleGroup? muscleGroup) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [muscleGroup]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i12.Future<List<_i20.MuscleGroup>> getAllMuscleGroups() =>
      (super.noSuchMethod(
            Invocation.method(#getAllMuscleGroups, []),
            returnValue: _i12.Future<List<_i20.MuscleGroup>>.value(
              <_i20.MuscleGroup>[],
            ),
          )
          as _i12.Future<List<_i20.MuscleGroup>>);

  @override
  _i12.Future<_i20.MuscleGroup?> getMuscleGroupByName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getMuscleGroupByName, [name]),
            returnValue: _i12.Future<_i20.MuscleGroup?>.value(),
          )
          as _i12.Future<_i20.MuscleGroup?>);

  @override
  _i12.Future<int> insert(_i20.MuscleGroup? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<List<int>> insertAll(List<_i20.MuscleGroup>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i12.Future<List<int>>.value(<int>[]),
          )
          as _i12.Future<List<int>>);

  @override
  _i12.Future<List<_i20.MuscleGroup>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i12.Future<List<_i20.MuscleGroup>>.value(
              <_i20.MuscleGroup>[],
            ),
          )
          as _i12.Future<List<_i20.MuscleGroup>>);

  @override
  _i12.Future<_i20.MuscleGroup?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i20.MuscleGroup?>.value(),
          )
          as _i12.Future<_i20.MuscleGroup?>);

  @override
  _i12.Future<int> update(_i20.MuscleGroup? model, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<List<_i20.MuscleGroup>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i12.Future<List<_i20.MuscleGroup>>.value(
              <_i20.MuscleGroup>[],
            ),
          )
          as _i12.Future<List<_i20.MuscleGroup>>);

  @override
  _i12.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}
