// Mocks generated by Mockito 5.4.6 from annotations
// in zenith/test/services/reorder_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:zenith/models/exercise.dart' as _i8;
import 'package:zenith/models/workout.dart' as _i2;
import 'package:zenith/models/workout_exercise.dart' as _i9;
import 'package:zenith/services/dao/workout_dao.dart' as _i4;
import 'package:zenith/services/dao/workout_exercise_dao.dart' as _i5;
import 'package:zenith/services/dao/workout_set_dao.dart' as _i6;
import 'package:zenith/services/workout_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWorkout_0 extends _i1.SmartFake implements _i2.Workout {
  _FakeWorkout_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WorkoutService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutService extends _i1.Mock implements _i3.WorkoutService {
  MockWorkoutService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Workout> get workouts =>
      (super.noSuchMethod(
            Invocation.getter(#workouts),
            returnValue: <_i2.Workout>[],
          )
          as List<_i2.Workout>);

  @override
  set workoutDao(_i4.WorkoutDao? dao) => super.noSuchMethod(
    Invocation.setter(#workoutDao, dao),
    returnValueForMissingStub: null,
  );

  @override
  set workoutExerciseDao(_i5.WorkoutExerciseDao? dao) => super.noSuchMethod(
    Invocation.setter(#workoutExerciseDao, dao),
    returnValueForMissingStub: null,
  );

  @override
  set workoutSetDao(_i6.WorkoutSetDao? dao) => super.noSuchMethod(
    Invocation.setter(#workoutSetDao, dao),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> loadData() =>
      (super.noSuchMethod(
            Invocation.method(#loadData, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveData() =>
      (super.noSuchMethod(
            Invocation.method(#saveData, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.Workout> createWorkout(String? name, {String? folderId}) =>
      (super.noSuchMethod(
            Invocation.method(#createWorkout, [name], {#folderId: folderId}),
            returnValue: _i7.Future<_i2.Workout>.value(
              _FakeWorkout_0(
                this,
                Invocation.method(
                  #createWorkout,
                  [name],
                  {#folderId: folderId},
                ),
              ),
            ),
          )
          as _i7.Future<_i2.Workout>);

  @override
  _i7.Future<void> updateWorkout(_i2.Workout? workout) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkout, [workout]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteWorkout(String? workoutId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkout, [workoutId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> moveWorkoutToFolder(String? workoutId, String? folderId) =>
      (super.noSuchMethod(
            Invocation.method(#moveWorkoutToFolder, [workoutId, folderId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> reorderWorkoutsInFolder(
    String? folderId,
    int? oldIndex,
    int? newIndex,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reorderWorkoutsInFolder, [
              folderId,
              oldIndex,
              newIndex,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> reorderExercisesInWorkout(
    String? workoutId,
    int? oldIndex,
    int? newIndex,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reorderExercisesInWorkout, [
              workoutId,
              oldIndex,
              newIndex,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> addExerciseToWorkout(
    String? workoutId,
    _i8.Exercise? exerciseDetail,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addExerciseToWorkout, [
              workoutId,
              exerciseDetail,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> removeExerciseFromWorkout(
    String? workoutId,
    String? exerciseId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeExerciseFromWorkout, [
              workoutId,
              exerciseId,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateWorkoutExercise(
    String? workoutId,
    _i9.WorkoutExercise? exercise,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkoutExercise, [workoutId, exercise]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> addSetToExercise(
    String? workoutId,
    String? exerciseId, {
    int? targetReps = 10,
    double? targetWeight = 0.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addSetToExercise,
              [workoutId, exerciseId],
              {#targetReps: targetReps, #targetWeight: targetWeight},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> removeSetFromExercise(
    String? workoutId,
    String? exerciseId,
    String? setId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeSetFromExercise, [
              workoutId,
              exerciseId,
              setId,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateSet(
    String? workoutId,
    String? exerciseId,
    String? setId, {
    int? targetReps,
    double? targetWeight,
    int? targetRestSeconds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateSet,
              [workoutId, exerciseId, setId],
              {
                #targetReps: targetReps,
                #targetWeight: targetWeight,
                #targetRestSeconds: targetRestSeconds,
              },
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  List<_i2.Workout> getWorkoutsInFolder(String? folderId) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutsInFolder, [folderId]),
            returnValue: <_i2.Workout>[],
          )
          as List<_i2.Workout>);

  @override
  List<_i2.Workout> getWorkoutsNotInFolder() =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutsNotInFolder, []),
            returnValue: <_i2.Workout>[],
          )
          as List<_i2.Workout>);

  @override
  _i2.Workout? getWorkoutById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getWorkoutById, [id]))
          as _i2.Workout?);

  @override
  _i7.Future<void> clearUserWorkouts() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserWorkouts, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
