// Mocks generated by Mockito 5.4.6 from annotations
// in zenith/test/services/user_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:sqflite/sqflite.dart' as _i2;
import 'package:zenith/models/user_data.dart' as _i3;
import 'package:zenith/services/dao/user_dao.dart' as _i4;
import 'package:zenith/services/dao/weight_entry_dao.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserData_1 extends _i1.SmartFake implements _i3.UserData {
  _FakeUserData_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWeightEntry_2 extends _i1.SmartFake implements _i3.WeightEntry {
  _FakeWeightEntry_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDao extends _i1.Mock implements _i4.UserDao {
  MockUserDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i6.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i6.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i6.Future<_i2.Database>);

  @override
  _i3.UserData fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeUserData_1(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i3.UserData);

  @override
  Map<String, dynamic> toMap(_i3.UserData? userData) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [userData]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i6.Future<_i3.UserData?> getUserDataById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUserDataById, [id]),
            returnValue: _i6.Future<_i3.UserData?>.value(),
          )
          as _i6.Future<_i3.UserData?>);

  @override
  _i6.Future<int> updateUserData(_i3.UserData? userData) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserData, [userData]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> insert(_i3.UserData? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<int>> insertAll(List<_i3.UserData>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i6.Future<List<int>>.value(<int>[]),
          )
          as _i6.Future<List<int>>);

  @override
  _i6.Future<List<_i3.UserData>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i6.Future<List<_i3.UserData>>.value(<_i3.UserData>[]),
          )
          as _i6.Future<List<_i3.UserData>>);

  @override
  _i6.Future<_i3.UserData?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i6.Future<_i3.UserData?>.value(),
          )
          as _i6.Future<_i3.UserData?>);

  @override
  _i6.Future<int> update(_i3.UserData? model, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i3.UserData>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i6.Future<List<_i3.UserData>>.value(<_i3.UserData>[]),
          )
          as _i6.Future<List<_i3.UserData>>);

  @override
  _i6.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);
}

/// A class which mocks [WeightEntryDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeightEntryDao extends _i1.Mock implements _i7.WeightEntryDao {
  MockWeightEntryDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i6.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i6.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i6.Future<_i2.Database>);

  @override
  _i3.WeightEntry fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeWeightEntry_2(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i3.WeightEntry);

  @override
  Map<String, dynamic> toMap(_i3.WeightEntry? weightEntry) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [weightEntry]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i6.Future<List<_i3.WeightEntry>> getWeightEntriesByUserId(
    String? userDataId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWeightEntriesByUserId, [userDataId]),
            returnValue: _i6.Future<List<_i3.WeightEntry>>.value(
              <_i3.WeightEntry>[],
            ),
          )
          as _i6.Future<List<_i3.WeightEntry>>);

  @override
  _i6.Future<int> addWeightEntryForUser(
    String? userDataId,
    _i3.WeightEntry? weightEntry,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addWeightEntryForUser, [
              userDataId,
              weightEntry,
            ]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> updateWeightEntry(
    String? userDataId,
    _i3.WeightEntry? weightEntry,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateWeightEntry, [userDataId, weightEntry]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> deleteWeightEntry(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWeightEntry, [id]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> insert(_i3.WeightEntry? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<int>> insertAll(List<_i3.WeightEntry>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i6.Future<List<int>>.value(<int>[]),
          )
          as _i6.Future<List<int>>);

  @override
  _i6.Future<List<_i3.WeightEntry>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i6.Future<List<_i3.WeightEntry>>.value(
              <_i3.WeightEntry>[],
            ),
          )
          as _i6.Future<List<_i3.WeightEntry>>);

  @override
  _i6.Future<_i3.WeightEntry?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i6.Future<_i3.WeightEntry?>.value(),
          )
          as _i6.Future<_i3.WeightEntry?>);

  @override
  _i6.Future<int> update(_i3.WeightEntry? model, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i3.WeightEntry>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i6.Future<List<_i3.WeightEntry>>.value(
              <_i3.WeightEntry>[],
            ),
          )
          as _i6.Future<List<_i3.WeightEntry>>);

  @override
  _i6.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);
}
