// Mocks generated by Mockito 5.4.6 from annotations
// in zenith/test/services/workout_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:sqflite/sqflite.dart' as _i2;
import 'package:zenith/models/workout.dart' as _i3;
import 'package:zenith/models/workout_exercise.dart' as _i5;
import 'package:zenith/models/workout_folder.dart' as _i4;
import 'package:zenith/models/workout_set.dart' as _i6;
import 'package:zenith/services/dao/workout_dao.dart' as _i7;
import 'package:zenith/services/dao/workout_exercise_dao.dart' as _i11;
import 'package:zenith/services/dao/workout_folder_dao.dart' as _i10;
import 'package:zenith/services/dao/workout_set_dao.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWorkout_1 extends _i1.SmartFake implements _i3.Workout {
  _FakeWorkout_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWorkoutFolder_2 extends _i1.SmartFake implements _i4.WorkoutFolder {
  _FakeWorkoutFolder_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWorkoutExercise_3 extends _i1.SmartFake
    implements _i5.WorkoutExercise {
  _FakeWorkoutExercise_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWorkoutSet_4 extends _i1.SmartFake implements _i6.WorkoutSet {
  _FakeWorkoutSet_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WorkoutDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutDao extends _i1.Mock implements _i7.WorkoutDao {
  MockWorkoutDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i9.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i9.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i9.Future<_i2.Database>);

  @override
  _i3.Workout fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeWorkout_1(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i3.Workout);

  @override
  Map<String, dynamic> toMap(_i3.Workout? workout) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [workout]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i9.Future<_i3.Workout?> getWorkoutById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutById, [id]),
            returnValue: _i9.Future<_i3.Workout?>.value(),
          )
          as _i9.Future<_i3.Workout?>);

  @override
  _i9.Future<List<_i3.Workout>> getAllWorkouts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllWorkouts, []),
            returnValue: _i9.Future<List<_i3.Workout>>.value(<_i3.Workout>[]),
          )
          as _i9.Future<List<_i3.Workout>>);

  @override
  _i9.Future<List<_i3.Workout>> getWorkoutsByFolderId(String? folderId) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutsByFolderId, [folderId]),
            returnValue: _i9.Future<List<_i3.Workout>>.value(<_i3.Workout>[]),
          )
          as _i9.Future<List<_i3.Workout>>);

  @override
  _i9.Future<List<_i3.Workout>> getWorkoutsByStatus(
    _i3.WorkoutStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutsByStatus, [status]),
            returnValue: _i9.Future<List<_i3.Workout>>.value(<_i3.Workout>[]),
          )
          as _i9.Future<List<_i3.Workout>>);

  @override
  _i9.Future<List<_i3.Workout>> getTemplateWorkouts() =>
      (super.noSuchMethod(
            Invocation.method(#getTemplateWorkouts, []),
            returnValue: _i9.Future<List<_i3.Workout>>.value(<_i3.Workout>[]),
          )
          as _i9.Future<List<_i3.Workout>>);

  @override
  _i9.Future<List<_i3.Workout>> getInProgressWorkouts() =>
      (super.noSuchMethod(
            Invocation.method(#getInProgressWorkouts, []),
            returnValue: _i9.Future<List<_i3.Workout>>.value(<_i3.Workout>[]),
          )
          as _i9.Future<List<_i3.Workout>>);

  @override
  _i9.Future<List<_i3.Workout>> getCompletedWorkouts() =>
      (super.noSuchMethod(
            Invocation.method(#getCompletedWorkouts, []),
            returnValue: _i9.Future<List<_i3.Workout>>.value(<_i3.Workout>[]),
          )
          as _i9.Future<List<_i3.Workout>>);

  @override
  _i9.Future<List<_i3.Workout>> getWorkoutsByTemplateId(String? templateId) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutsByTemplateId, [templateId]),
            returnValue: _i9.Future<List<_i3.Workout>>.value(<_i3.Workout>[]),
          )
          as _i9.Future<List<_i3.Workout>>);

  @override
  _i9.Future<List<_i3.Workout>> getWorkoutsInDateRange(
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutsInDateRange, [startDate, endDate]),
            returnValue: _i9.Future<List<_i3.Workout>>.value(<_i3.Workout>[]),
          )
          as _i9.Future<List<_i3.Workout>>);

  @override
  _i9.Future<int> updateWorkout(_i3.Workout? workout) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkout, [workout]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<int> deleteWorkout(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkout, [id]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<int> insert(_i3.Workout? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<List<int>> insertAll(List<_i3.Workout>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i9.Future<List<int>>.value(<int>[]),
          )
          as _i9.Future<List<int>>);

  @override
  _i9.Future<List<_i3.Workout>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i9.Future<List<_i3.Workout>>.value(<_i3.Workout>[]),
          )
          as _i9.Future<List<_i3.Workout>>);

  @override
  _i9.Future<_i3.Workout?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i9.Future<_i3.Workout?>.value(),
          )
          as _i9.Future<_i3.Workout?>);

  @override
  _i9.Future<int> update(_i3.Workout? model, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<List<_i3.Workout>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i9.Future<List<_i3.Workout>>.value(<_i3.Workout>[]),
          )
          as _i9.Future<List<_i3.Workout>>);

  @override
  _i9.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);
}

/// A class which mocks [WorkoutFolderDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutFolderDao extends _i1.Mock implements _i10.WorkoutFolderDao {
  MockWorkoutFolderDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i9.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i9.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i9.Future<_i2.Database>);

  @override
  _i4.WorkoutFolder fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeWorkoutFolder_2(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i4.WorkoutFolder);

  @override
  Map<String, dynamic> toMap(_i4.WorkoutFolder? workoutFolder) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [workoutFolder]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i9.Future<_i4.WorkoutFolder?> getWorkoutFolderById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutFolderById, [id]),
            returnValue: _i9.Future<_i4.WorkoutFolder?>.value(),
          )
          as _i9.Future<_i4.WorkoutFolder?>);

  @override
  _i9.Future<List<_i4.WorkoutFolder>> getAllWorkoutFoldersOrdered() =>
      (super.noSuchMethod(
            Invocation.method(#getAllWorkoutFoldersOrdered, []),
            returnValue: _i9.Future<List<_i4.WorkoutFolder>>.value(
              <_i4.WorkoutFolder>[],
            ),
          )
          as _i9.Future<List<_i4.WorkoutFolder>>);

  @override
  _i9.Future<int> updateWorkoutFolder(_i4.WorkoutFolder? workoutFolder) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkoutFolder, [workoutFolder]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<int> deleteWorkoutFolder(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkoutFolder, [id]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<int> insert(_i4.WorkoutFolder? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<List<int>> insertAll(List<_i4.WorkoutFolder>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i9.Future<List<int>>.value(<int>[]),
          )
          as _i9.Future<List<int>>);

  @override
  _i9.Future<List<_i4.WorkoutFolder>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i9.Future<List<_i4.WorkoutFolder>>.value(
              <_i4.WorkoutFolder>[],
            ),
          )
          as _i9.Future<List<_i4.WorkoutFolder>>);

  @override
  _i9.Future<_i4.WorkoutFolder?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i9.Future<_i4.WorkoutFolder?>.value(),
          )
          as _i9.Future<_i4.WorkoutFolder?>);

  @override
  _i9.Future<int> update(_i4.WorkoutFolder? model, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<List<_i4.WorkoutFolder>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i9.Future<List<_i4.WorkoutFolder>>.value(
              <_i4.WorkoutFolder>[],
            ),
          )
          as _i9.Future<List<_i4.WorkoutFolder>>);

  @override
  _i9.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);
}

/// A class which mocks [WorkoutExerciseDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutExerciseDao extends _i1.Mock
    implements _i11.WorkoutExerciseDao {
  MockWorkoutExerciseDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i9.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i9.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i9.Future<_i2.Database>);

  @override
  _i5.WorkoutExercise fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeWorkoutExercise_3(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i5.WorkoutExercise);

  @override
  Map<String, dynamic> toMap(_i5.WorkoutExercise? workoutExercise) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [workoutExercise]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i9.Future<_i5.WorkoutExercise?> getWorkoutExerciseById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutExerciseById, [id]),
            returnValue: _i9.Future<_i5.WorkoutExercise?>.value(),
          )
          as _i9.Future<_i5.WorkoutExercise?>);

  @override
  _i9.Future<List<_i5.WorkoutExercise>> getWorkoutExercisesByWorkoutId(
    String? workoutId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutExercisesByWorkoutId, [workoutId]),
            returnValue: _i9.Future<List<_i5.WorkoutExercise>>.value(
              <_i5.WorkoutExercise>[],
            ),
          )
          as _i9.Future<List<_i5.WorkoutExercise>>);

  @override
  _i9.Future<List<_i5.WorkoutExercise>> getWorkoutExercisesByExerciseSlug(
    String? exerciseSlug,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutExercisesByExerciseSlug, [
              exerciseSlug,
            ]),
            returnValue: _i9.Future<List<_i5.WorkoutExercise>>.value(
              <_i5.WorkoutExercise>[],
            ),
          )
          as _i9.Future<List<_i5.WorkoutExercise>>);

  @override
  _i9.Future<int> updateWorkoutExercise(_i5.WorkoutExercise? workoutExercise) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkoutExercise, [workoutExercise]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<int> deleteWorkoutExercise(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkoutExercise, [id]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<int> deleteWorkoutExercisesByWorkoutId(String? workoutId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkoutExercisesByWorkoutId, [workoutId]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<int> insert(_i5.WorkoutExercise? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<List<int>> insertAll(List<_i5.WorkoutExercise>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i9.Future<List<int>>.value(<int>[]),
          )
          as _i9.Future<List<int>>);

  @override
  _i9.Future<List<_i5.WorkoutExercise>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i9.Future<List<_i5.WorkoutExercise>>.value(
              <_i5.WorkoutExercise>[],
            ),
          )
          as _i9.Future<List<_i5.WorkoutExercise>>);

  @override
  _i9.Future<_i5.WorkoutExercise?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i9.Future<_i5.WorkoutExercise?>.value(),
          )
          as _i9.Future<_i5.WorkoutExercise?>);

  @override
  _i9.Future<int> update(
    _i5.WorkoutExercise? model, {
    String? idColumn = 'id',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<List<_i5.WorkoutExercise>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i9.Future<List<_i5.WorkoutExercise>>.value(
              <_i5.WorkoutExercise>[],
            ),
          )
          as _i9.Future<List<_i5.WorkoutExercise>>);

  @override
  _i9.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);
}

/// A class which mocks [WorkoutSetDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutSetDao extends _i1.Mock implements _i12.WorkoutSetDao {
  MockWorkoutSetDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i9.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i9.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i9.Future<_i2.Database>);

  @override
  _i6.WorkoutSet fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeWorkoutSet_4(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i6.WorkoutSet);

  @override
  Map<String, dynamic> toMap(_i6.WorkoutSet? workoutSet) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [workoutSet]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i9.Future<_i6.WorkoutSet?> getWorkoutSetById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutSetById, [id]),
            returnValue: _i9.Future<_i6.WorkoutSet?>.value(),
          )
          as _i9.Future<_i6.WorkoutSet?>);

  @override
  _i9.Future<List<_i6.WorkoutSet>> getWorkoutSetsByWorkoutExerciseId(
    String? workoutExerciseId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutSetsByWorkoutExerciseId, [
              workoutExerciseId,
            ]),
            returnValue: _i9.Future<List<_i6.WorkoutSet>>.value(
              <_i6.WorkoutSet>[],
            ),
          )
          as _i9.Future<List<_i6.WorkoutSet>>);

  @override
  _i9.Future<List<_i6.WorkoutSet>> getCompletedWorkoutSetsByWorkoutExerciseId(
    String? workoutExerciseId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCompletedWorkoutSetsByWorkoutExerciseId, [
              workoutExerciseId,
            ]),
            returnValue: _i9.Future<List<_i6.WorkoutSet>>.value(
              <_i6.WorkoutSet>[],
            ),
          )
          as _i9.Future<List<_i6.WorkoutSet>>);

  @override
  _i9.Future<int> updateWorkoutSet(_i6.WorkoutSet? workoutSet) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkoutSet, [workoutSet]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<int> deleteWorkoutSet(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkoutSet, [id]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<int> deleteWorkoutSetsByWorkoutExerciseId(
    String? workoutExerciseId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkoutSetsByWorkoutExerciseId, [
              workoutExerciseId,
            ]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<int> insert(_i6.WorkoutSet? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<List<int>> insertAll(List<_i6.WorkoutSet>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i9.Future<List<int>>.value(<int>[]),
          )
          as _i9.Future<List<int>>);

  @override
  _i9.Future<List<_i6.WorkoutSet>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i9.Future<List<_i6.WorkoutSet>>.value(
              <_i6.WorkoutSet>[],
            ),
          )
          as _i9.Future<List<_i6.WorkoutSet>>);

  @override
  _i9.Future<_i6.WorkoutSet?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i9.Future<_i6.WorkoutSet?>.value(),
          )
          as _i9.Future<_i6.WorkoutSet?>);

  @override
  _i9.Future<int> update(_i6.WorkoutSet? model, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<List<_i6.WorkoutSet>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i9.Future<List<_i6.WorkoutSet>>.value(
              <_i6.WorkoutSet>[],
            ),
          )
          as _i9.Future<List<_i6.WorkoutSet>>);

  @override
  _i9.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);
}
