// Mocks generated by Mockito 5.4.6 from annotations
// in zenith/test/services/workout_template_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:logging/logging.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:sqflite/sqflite.dart' as _i3;
import 'package:zenith/models/workout_folder.dart' as _i5;
import 'package:zenith/models/workout_template.dart' as _i4;
import 'package:zenith/services/dao/workout_folder_dao.dart' as _i9;
import 'package:zenith/services/dao/workout_template_dao.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLogger_0 extends _i1.SmartFake implements _i2.Logger {
  _FakeLogger_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabase_1 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWorkoutTemplate_2 extends _i1.SmartFake
    implements _i4.WorkoutTemplate {
  _FakeWorkoutTemplate_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWorkoutFolder_3 extends _i1.SmartFake implements _i5.WorkoutFolder {
  _FakeWorkoutFolder_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WorkoutTemplateDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutTemplateDao extends _i1.Mock
    implements _i6.WorkoutTemplateDao {
  MockWorkoutTemplateDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i2.Logger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeLogger_0(this, Invocation.getter(#logger)),
          )
          as _i2.Logger);

  @override
  _i8.Future<_i3.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i8.Future<_i3.Database>.value(
              _FakeDatabase_1(this, Invocation.getter(#database)),
            ),
          )
          as _i8.Future<_i3.Database>);

  @override
  _i4.WorkoutTemplate fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeWorkoutTemplate_2(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i4.WorkoutTemplate);

  @override
  Map<String, dynamic> toMap(_i4.WorkoutTemplate? workoutTemplate) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [workoutTemplate]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i8.Future<_i4.WorkoutTemplate?> getWorkoutTemplateById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutTemplateById, [id]),
            returnValue: _i8.Future<_i4.WorkoutTemplate?>.value(),
          )
          as _i8.Future<_i4.WorkoutTemplate?>);

  @override
  _i8.Future<List<_i4.WorkoutTemplate>> getWorkoutTemplatesByFolderId(
    String? folderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutTemplatesByFolderId, [folderId]),
            returnValue: _i8.Future<List<_i4.WorkoutTemplate>>.value(
              <_i4.WorkoutTemplate>[],
            ),
          )
          as _i8.Future<List<_i4.WorkoutTemplate>>);

  @override
  _i8.Future<List<_i4.WorkoutTemplate>> getWorkoutTemplatesWithoutFolder() =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutTemplatesWithoutFolder, []),
            returnValue: _i8.Future<List<_i4.WorkoutTemplate>>.value(
              <_i4.WorkoutTemplate>[],
            ),
          )
          as _i8.Future<List<_i4.WorkoutTemplate>>);

  @override
  _i8.Future<List<_i4.WorkoutTemplate>> getAllWorkoutTemplatesOrdered() =>
      (super.noSuchMethod(
            Invocation.method(#getAllWorkoutTemplatesOrdered, []),
            returnValue: _i8.Future<List<_i4.WorkoutTemplate>>.value(
              <_i4.WorkoutTemplate>[],
            ),
          )
          as _i8.Future<List<_i4.WorkoutTemplate>>);

  @override
  _i8.Future<int> updateWorkoutTemplate(_i4.WorkoutTemplate? workoutTemplate) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkoutTemplate, [workoutTemplate]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> deleteWorkoutTemplate(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkoutTemplate, [id]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> updateLastUsed(String? id, String? timestamp) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastUsed, [id, timestamp]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<List<_i4.WorkoutTemplate>> getWorkoutTemplatesByLastUsed({
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutTemplatesByLastUsed, [], {
              #limit: limit,
            }),
            returnValue: _i8.Future<List<_i4.WorkoutTemplate>>.value(
              <_i4.WorkoutTemplate>[],
            ),
          )
          as _i8.Future<List<_i4.WorkoutTemplate>>);

  @override
  _i8.Future<int> insert(_i4.WorkoutTemplate? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<List<int>> insertAll(List<_i4.WorkoutTemplate>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i8.Future<List<int>>.value(<int>[]),
          )
          as _i8.Future<List<int>>);

  @override
  _i8.Future<List<_i4.WorkoutTemplate>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i8.Future<List<_i4.WorkoutTemplate>>.value(
              <_i4.WorkoutTemplate>[],
            ),
          )
          as _i8.Future<List<_i4.WorkoutTemplate>>);

  @override
  _i8.Future<_i4.WorkoutTemplate?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i8.Future<_i4.WorkoutTemplate?>.value(),
          )
          as _i8.Future<_i4.WorkoutTemplate?>);

  @override
  _i8.Future<int> update(
    _i4.WorkoutTemplate? model, {
    String? idColumn = 'id',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<List<_i4.WorkoutTemplate>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i8.Future<List<_i4.WorkoutTemplate>>.value(
              <_i4.WorkoutTemplate>[],
            ),
          )
          as _i8.Future<List<_i4.WorkoutTemplate>>);

  @override
  _i8.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);
}

/// A class which mocks [WorkoutFolderDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutFolderDao extends _i1.Mock implements _i9.WorkoutFolderDao {
  MockWorkoutFolderDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  _i2.Logger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeLogger_0(this, Invocation.getter(#logger)),
          )
          as _i2.Logger);

  @override
  _i8.Future<_i3.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i8.Future<_i3.Database>.value(
              _FakeDatabase_1(this, Invocation.getter(#database)),
            ),
          )
          as _i8.Future<_i3.Database>);

  @override
  _i5.WorkoutFolder fromMap(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromMap, [map]),
            returnValue: _FakeWorkoutFolder_3(
              this,
              Invocation.method(#fromMap, [map]),
            ),
          )
          as _i5.WorkoutFolder);

  @override
  Map<String, dynamic> toMap(_i5.WorkoutFolder? workoutFolder) =>
      (super.noSuchMethod(
            Invocation.method(#toMap, [workoutFolder]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i8.Future<_i5.WorkoutFolder?> getWorkoutFolderById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutFolderById, [id]),
            returnValue: _i8.Future<_i5.WorkoutFolder?>.value(),
          )
          as _i8.Future<_i5.WorkoutFolder?>);

  @override
  _i8.Future<List<_i5.WorkoutFolder>> getAllWorkoutFoldersOrdered() =>
      (super.noSuchMethod(
            Invocation.method(#getAllWorkoutFoldersOrdered, []),
            returnValue: _i8.Future<List<_i5.WorkoutFolder>>.value(
              <_i5.WorkoutFolder>[],
            ),
          )
          as _i8.Future<List<_i5.WorkoutFolder>>);

  @override
  _i8.Future<int> updateWorkoutFolder(_i5.WorkoutFolder? workoutFolder) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkoutFolder, [workoutFolder]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> deleteWorkoutFolder(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkoutFolder, [id]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> insert(_i5.WorkoutFolder? model) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [model]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<List<int>> insertAll(List<_i5.WorkoutFolder>? models) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [models]),
            returnValue: _i8.Future<List<int>>.value(<int>[]),
          )
          as _i8.Future<List<int>>);

  @override
  _i8.Future<List<_i5.WorkoutFolder>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i8.Future<List<_i5.WorkoutFolder>>.value(
              <_i5.WorkoutFolder>[],
            ),
          )
          as _i8.Future<List<_i5.WorkoutFolder>>);

  @override
  _i8.Future<_i5.WorkoutFolder?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i8.Future<_i5.WorkoutFolder?>.value(),
          )
          as _i8.Future<_i5.WorkoutFolder?>);

  @override
  _i8.Future<int> update(_i5.WorkoutFolder? model, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#update, [model], {#idColumn: idColumn}),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> delete(String? id, {String? idColumn = 'id'}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id], {#idColumn: idColumn}),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<List<_i5.WorkoutFolder>> rawQuery(
    String? sql, [
    List<dynamic>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#rawQuery, [sql, arguments]),
            returnValue: _i8.Future<List<_i5.WorkoutFolder>>.value(
              <_i5.WorkoutFolder>[],
            ),
          )
          as _i8.Future<List<_i5.WorkoutFolder>>);

  @override
  _i8.Future<int> rawUpdate(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawUpdate, [sql, arguments]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> rawDelete(String? sql, [List<dynamic>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#rawDelete, [sql, arguments]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);
}
